import { NextRequest, NextResponse } from 'next/server'
import { db } from '@/lib/db'
import { getTokenPayload } from '@/lib/auth'

// GET /api/admin/system-health — Cross-reference audit logs + system alerts from last 24h
export async function GET(request: NextRequest) {
  try {
    const payload = await getTokenPayload(request)
    if (!payload || payload.role !== 'SUPER_ADMIN') {
      return NextResponse.json({ error: 'Acceso denegado. Se requiere rol SUPER_ADMIN.' }, { status: 403 })
    }

    const now = new Date()
    const twentyFourHoursAgo = new Date(now.getTime() - 24 * 60 * 60 * 1000)

    // ── 1. Fetch error-type audit logs from last 24h ──
    const errorActions = ['SYSTEM_ERROR', 'SECURITY_BREACH', 'ERROR', 'FAILURE', 'EXCEPTION']
    const auditErrors = await db.auditLog.findMany({
      where: {
        createdAt: { gte: twentyFourHoursAgo },
        OR: errorActions.map(action => ({
          action: { contains: action },
        })),
      },
      include: {
        company: { select: { id: true, name: true } },
      },
      orderBy: { createdAt: 'desc' },
    })

    // Count errors by action type across all companies
    const errorByAction: Record<string, number> = {}
    const errorCompaniesByAction: Record<string, Set<string>> = {}

    for (const log of auditErrors) {
      const actionKey = log.action.toUpperCase()
      errorByAction[actionKey] = (errorByAction[actionKey] || 0) + 1

      if (!errorCompaniesByAction[actionKey]) {
        errorCompaniesByAction[actionKey] = new Set()
      }
      errorCompaniesByAction[actionKey].add(log.companyId)
    }

    // Top errors sorted by count
    const topErrors = Object.entries(errorByAction)
      .sort(([, a], [, b]) => b - a)
      .slice(0, 10)
      .map(([action, count]) => ({
        action,
        count,
        affectedCompanies: errorCompaniesByAction[action]?.size || 0,
      }))

    // Detect Global Incidents: error type appearing in 3+ companies
    const globalIncidents: Array<{
      action: string
      affectedCompanies: number
      companyNames: string[]
      isAutoGenerated: boolean
    }> = []

    for (const [action, companies] of Object.entries(errorCompaniesByAction)) {
      if (companies.size >= 3) {
        // Get company names for this error type
        const names = auditErrors
          .filter(log => log.action.toUpperCase() === action && log.companyId)
          .map(log => log.company.name)
          .filter((v, i, a) => a.indexOf(v) === i)
          .slice(0, 10)

        globalIncidents.push({
          action,
          affectedCompanies: companies.size,
          companyNames: names,
          isAutoGenerated: true,
        })
      }
    }

    // ── 2. Fetch SystemAlerts from last 24h ──
    const recentAlerts = await db.systemAlert.findMany({
      where: {
        createdAt: { gte: twentyFourHoursAgo },
      },
      orderBy: { createdAt: 'desc' },
    })

    const criticalCount = recentAlerts.filter(a => a.severity === 'CRITICAL').length
    const unacknowledgedCount = recentAlerts.filter(a => !a.isAcknowledged).length

    const alertsByType: Record<string, number> = {}
    for (const alert of recentAlerts) {
      alertsByType[alert.type] = (alertsByType[alert.type] || 0) + 1
    }

    // ── 3. Determine overall health status ──
    let healthStatus: 'HEALTHY' | 'DEGRADED' | 'CRITICAL'
    if (globalIncidents.length > 0 || criticalCount > 10) {
      healthStatus = 'CRITICAL'
    } else if (auditErrors.length > 50 || unacknowledgedCount > 20 || criticalCount > 3) {
      healthStatus = 'DEGRADED'
    } else {
      healthStatus = 'HEALTHY'
    }

    return NextResponse.json({
      healthStatus,
      totalErrors24h: auditErrors.length,
      topErrors,
      globalIncidents,
      alerts24h: {
        total: recentAlerts.length,
        critical: criticalCount,
        unacknowledged: unacknowledgedCount,
        byType: alertsByType,
      },
      lastChecked: now.toISOString(),
    })
  } catch (error: unknown) {
    console.error('[System Health GET] Error:', error)
    return NextResponse.json(
      { error: error instanceof Error ? error.message : 'Error interno del servidor' },
      { status: 500 }
    )
  }
}
